apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "meeting-intel-common.fullname" . }}
  labels:
    {{- include "meeting-intel-common.labels" . | nindent 4 }}
data:
  config.json: |
    {{- .Values.config | toJson | nindent 4 }}
