apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: whisper-models
  namespace: {{ .Values.namespace }}
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
