{{- range .Values.topics }}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: {{ . }}
  namespace: {{ $.Values.namespace }}
  labels:
    strimzi.io/cluster: {{ $.Values.clusterName }}
spec:
  partitions: {{ $.Values.topicDefaults.partitions }}
  replicas: {{ $.Values.topicDefaults.replicas }}
---
{{- end }}
